In [1]:
import numpy as np
# ---------------------------------------------------
# (1) Euclidean Distance in 2D Space
# Formula: d = sqrt((x2 - x1)^2 + (y2 - y1)^2)
# ---------------------------------------------------
# Define two points (x1, y1) and (x2, y2)
point1 = np.array([2, 3])
point2 = np.array([6, 7])
# Calculate Euclidean Distance
distance = np.sqrt(np.sum((point2 - point1) ** 2))
print("Point 1:", point1)
print("Point 2:", point2)
print("Euclidean Distance:", distance)
# ---------------------------------------------------
# (2) Dot Product of Two Matrices
# ---------------------------------------------------
# Define two matrices
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])
# Dot product using NumPy
dot_product = np.dot(A, B)
print("\nMatrix A:\n", A)
print("\nMatrix B:\n", B)
print("\nDot Product (A x B):\n", dot_product)

Point 1: [2 3]
Point 2: [6 7]
Euclidean Distance: 5.656854249492381

Matrix A:
 [[1 2]
 [3 4]]

Matrix B:
 [[5 6]
 [7 8]]

Dot Product (A x B):
 [[19 22]
 [43 50]]
